In [1]:
import numpy as np

## Creating Numpy Arrays From Python Lists
(Tạo mảng Numpy từ danh sách Python)

In [2]:
# np.array([1,2,3,4]) tạo ra một mảng một chiều gồm 4 phần tử: 1, 2, 3, và 4 bằng thư viện NumPy của Python.
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
# Array có thể chứa Float và Int
[3.14, 4,2,3]

[3.14, 4, 2, 3]

In [4]:
# Khi trong array có 2 kiểu dữ liệu thì nó sẽ kiểu dữ liệu lớn hơn
# Dưới đây kiểu dữ liệu Float64 lớn hơn Int32 nên sẽ chuyển dữ liệu trong array sang kiểu dữ liệu lớn hơn là Float64
np.array([3.14, 4 , 2 , 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
# Ép kiểu dữ liệu của Array sang Float 32bit
c = np.array([1,2,3,4],dtype = 'float32')
c

array([1., 2., 3., 4.], dtype=float32)

In [6]:
# shape trả về kích trước của mảng (hàng,cột)
a2 = np.array([[1,2,3,4]])
a2.shape

(1, 4)

In [7]:
# ndim trả về số chiều của mảng
a2.ndim

2

In [8]:
# dtype trả về kiểu dữ liệu của phần tử trong mảng
a2.dtype

dtype('int32')

In [9]:
# size trả về số lượng phần tử trong mảng
a2.size

4

## Creating Numpy Arrays From Scatch 
(Tạo mảng NumPy từ đầu)

##### zeros, ones, full, arange, linspace

In [10]:
# zeros là một hàm trong thư viện NumPy của Python được sử dụng để tạo ra một mảng mới với các phần tử bằng 0.
# Cú pháp sử dụng hàm zeros như sau: numpy.zeros(shape, dtype=float, order='C')
# Trong đó:
# shape: là tuple hoặc list chứa kích thước của mảng mới cần tạo.
# dtype: là kiểu dữ liệu của các phần tử trong mảng mới. Giá trị mặc định là float64.
# order: xác định cách mảng được lưu trữ trong bộ nhớ. Giá trị mặc định là 'C', tương đương với cách lưu trữ theo thứ tự "C-style", tức là theo chiều dọc.

np.zeros([4,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
# Tương tự như hàm zeros có điều nó sẽ giá trị phần tử trong mảng trả về là 1
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:

# arange là một hàm trong thư viện NumPy của Python để tạo ra một mảng các số nguyên hoặc số thực liên tiếp với một khoảng cách cố định giữa chúng.
# Cú pháp của hàm arange như sau: numpy.arange([start, ]stop, [step, ]dtype=None)
# Trong đó:
# start: giá trị đầu tiên trong mảng (mặc định là 0 nếu không được cung cấp).
# stop: giá trị cuối cùng trong mảng (không bao gồm giá trị này trong mảng).
# step: khoảng cách giữa các giá trị trong mảng (mặc định là 1 nếu không được cung cấp).
# dtype: kiểu dữ liệu của mảng (mặc định là kiểu dữ liệu của start nếu không được cung cấp).
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
# Hàm numpy.full trong thư viện NumPy được sử dụng để tạo một mảng với tất cả các phần tử có giá trị bằng nhau.
# Cú pháp của hàm numpy.full như sau: numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
# Trong đó:
# shape: kích thước của mảng được tạo ra (có thể là một tuple hoặc một số nguyên).
# fill_value: giá trị để điền vào tất cả các phần tử của mảng.
# dtype (tuỳ chọn): kiểu dữ liệu của mảng (mặc định là None, tức là sử dụng kiểu dữ liệu của fill_value).
# order (tuỳ chọn): thứ tự lưu trữ của mảng ('C' cho C-style, hoặc 'F' cho Fortran-style).
# like (tuỳ chọn): một mảng khác để sao chép kích thước và kiểu dữ liệu của mảng được tạo ra.
np.full([3,5],2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [14]:
# linspace là một hàm của thư viện NumPy được sử dụng để tạo ra một mảng Numpy chứa các giá trị được phân bố đều trong một khoảng giá trị cho trước.
# Cú pháp của hàm numpy.linspace như sau:numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# Trong đó:
# start: giá trị đầu tiên của khoảng giá trị.
# stop: giá trị cuối cùng của khoảng giá trị.
# num (tuỳ chọn): số lượng các giá trị được tạo ra (mặc định là 50).
# endpoint (tuỳ chọn): xác định xem giá trị stop có nằm trong khoảng giá trị được tạo ra hay không (mặc định là True).
# retstep (tuỳ chọn): xác định xem có trả về khoảng cách giữa các giá trị hay không (mặc định là False).
# dtype (tuỳ chọn): kiểu dữ liệu của mảng được tạo ra (mặc định là None, tức là sử dụng kiểu dữ liệu mặc định của NumPy).
# axis (tuỳ chọn): trục để tạo mảng (mặc định là 0).
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### random


In [15]:
np.random.seed(0) # trỏ vào 0

np.random.random((4,4)) # nhảy số ngẫu nhiên trong phạm vi từ 0.0 cho tới 1.0

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [16]:
np.random.seed(0) # trỏ vào 0
np.random.random((4,4)) # nhảy số ngẫu nhiên trong phạm vi từ 0.0 cho tới 1.0

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [17]:
# rand tương tự như random nhưng không cần ()
np.random.rand(4,4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [18]:
# ma trận 3x3 với các giá trị được lấy ngẫu nhiên theo phân phối chuẩn, với giá trị trung bình bằng 0 và độ lệch chuẩn bằng 1.
np.random.normal(0,1,(3,3)) 


array([[ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575]])

In [19]:
# ma trận 4x5 với giá trị ngẫu nhiên từ 0 - 10
np.random.randint(0,10,(4,5))

array([[1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3],
       [5, 9, 4, 4, 6],
       [4, 4, 3, 4, 4]])

## Array Indexing & Slicing


#### One-dimensional subarray (Mảng 1 chiều)

In [20]:
x1 = np.random.randint(20, size = 6)
x1

array([ 8, 14, 15,  3, 15, 13])

In [21]:
x1[0], x1[1]

(8, 14)

#### Multi-dimensional array (Mảng 2 chiều)

In [22]:
x2 = np.random.randint(10, size = (3,4))
x2

array([[5, 5, 0, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

In [23]:
x2[0,3],x2[2,3]

(1, 2)

In [24]:
x2[0,2] = 6

In [25]:
x2

array([[5, 5, 6, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

#### Slicing
x[start:stop:step]

In [26]:
x1

array([ 8, 14, 15,  3, 15, 13])

In [27]:
x1[0:3]

array([ 8, 14, 15])

In [28]:
# every other element, every 2 step
x1[::2]

array([ 8, 15, 15])

In [29]:
x2

array([[5, 5, 6, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

In [30]:
x2[0:3][0:3]
# Giả sử x2 là một mảng hai chiều, thì x2[0:2][0:3] được hiểu như sau:

# x2[0:2] sẽ trả về một mảng mới gồm các hàng từ hàng thứ 0 đến hàng thứ 1 của mảng x2 (lưu ý rằng chỉ số của hàng bắt đầu từ 0). Do đó, kết quả sẽ là một mảng hai chiều mới có số hàng là 2.
# Tiếp theo, với mảng hai chiều mới này, ta sử dụng chỉ số [0:3] để truy xuất các phần tử của các hàng trong mảng mới. Với chỉ số này, ta sẽ lấy các phần tử từ cột đầu tiên đến cột thứ 2 (lưu ý rằng chỉ số của cột cũng bắt đầu từ 0).
# Vậy kết quả cuối cùng sẽ là một mảng 2x3, bao gồm 2 hàng và 3 cột, chứa các phần tử của hàng 0 và 1 của mảng ban đầu, và cột 0 đến cột 2 của các hàng đó.

array([[5, 5, 6, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

#### Reshaping of Arrays & Transpose (Thay đổi hình dạng của mảng)

In [31]:
# shape trả về kích trước của mảng (hàng,cột)
grid = np.arange(1,10)
grid.shape

(9,)

In [32]:
# reshapre thay đổi kích thước của mảng
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
x = np.array([1,2,3])
x.shape

(3,)

In [34]:
x.reshape((1,3)).shape

(1, 3)

In [35]:
x = np.array([[1. ,2.],[3., 4.]])

In [36]:
x

array([[1., 2.],
       [3., 4.]])

In [37]:
#  được sử dụng để trả về ma trận chuyển vị (transpose) của mảng. Khi sử dụng T, các cột của mảng ban đầu trở thành các hàng của ma trận mới và ngược lại, 
# các hàng của mảng ban đầu trở thành các cột của ma trận mới.
x.T

array([[1., 3.],
       [2., 4.]])

### Array Concatenation(Nối mảng)  and Splitting(Tách mảng)

In [38]:
x =  np.array([1,2,3])
y =  np.array([3,4,5])

In [39]:
np.concatenate((x,y))

array([1, 2, 3, 3, 4, 5])

In [40]:
grid = np.array([[1,2,3], # Mặc định : axis = 0 nối theo hàng
                 [4,5,6]])
grid


array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate((grid,grid),axis = 1) # axis = 1 thì nối theo cột

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [42]:
#vstack nối mảng theo hàng
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

In [43]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [44]:
# horizontally stack the arrays: hstack : nối mảng theo cột
y = np.array([[99],
              [99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting of arrays

In [45]:
# split cắt mảng 
# cú pháp np.split(arr,[index])
# arr : mảng muốn cắt
# [index] : khoảng cách cắt
x = np.array([1,2,3,99,69,3,2,1])
x1, x2, x3, x4 =np.split(x,[2,4,6])

In [46]:
x1

array([1, 2])

In [47]:
x2

array([ 3, 99])

In [48]:
x3

array([69,  3])

In [49]:
x4

array([2, 1])

### Broadcasting and Vetorized operations
##### Broadcasting is simply a set of ruler for applying binary ufuns(e.g., additon, subtraction, multiplication, etc.) on arrays of different size (Broadcasting là một tập hợp các quy tắc để áp dụng các hàm hai ngôi (ví dụ như phép cộng, phép trừ, phép nhân, v.v.) trên các mảng có kích thước khác nhau. Broadcasting cho phép chúng ta thực hiện các phép toán này trên các mảng không cùng kích thước một cách dễ dàng và hiệu quả bằng cách tự động mở rộng một hoặc nhiều mảng để có cùng kích thước.)

In [50]:
a = np.arange(3)
a

array([0, 1, 2])

In [51]:
a + 5 #Broadcasting

array([5, 6, 7])

In [52]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
a.shape ,b.shape

((3,), (3, 3))

In [54]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [55]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [56]:
c = np.arange(3).reshape(3,1)

In [57]:
a

array([0, 1, 2])

In [58]:
c

array([[0],
       [1],
       [2]])

In [59]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### Manipulating & Comparing Arrays (Điều khiển và so sánh các mảng)
##### Aggregation(Tích lũy)
Aggregation = performkng the same operation on a number of things

Trong lập trình, aggregation (tích lũy) có nghĩa là thực hiện cùng một hoạt động trên một số lượng lớn các đối tượng. Trong NumPy, chúng ta có thể sử dụng các hàm tích lũy để thực hiện các hoạt động này trên các mảng.

Các hàm tích lũy thường được sử dụng để tính toán các giá trị thống kê của một mảng, chẳng hạn như tổng, trung bình, độ lệch chuẩn, v.v.

In [60]:
list_number = [1,2,3]

In [61]:
ll = np.array(list_number)

In [62]:
ll

array([1, 2, 3])

In [63]:
sum(ll) #Python sum()

6

In [64]:
np.sum(ll) #Numpy sum()

6

In [65]:
# Create a massive Numpy array (tạo 1 mảng Numpy rất lớn)
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.size
massive_array.shape

(10000,)

In [66]:
print("Python Sum")
%timeit sum(massive_array) # Python built-in function sum()
print("Numpy Sum")
%timeit np.sum(massive_array) # Numpy's np.sum()

Python Sum
616 µs ± 5.84 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
Numpy Sum
5.18 µs ± 87.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [67]:
# mean : trung bình mảng
np.mean(massive_array)

0.501465411241001

In [68]:
# max : giá trị lớn nhất trong mảng
np.max(massive_array)

0.9999709462497284

In [69]:
# min : giá trị nhỏ nhất trong mảng
np.min(massive_array)

2.0027530115096503e-05

In [70]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)
np.std(dog_height) # std : độ lệch chuẩn


147.32277488562318

In [71]:
# variance : một công cụ thống kê hữu ích vì nó cung cấp một đo lường định lượng cho độ biến thiên hoặc phân tán của tập dữ liệu. 
# Thường được sử dụng kết hợp với các đo lường thống kê khác, như giá trị trung bình và độ lệch chuẩn, để có một hiểu biết đầy đủ hơn về tập dữ liệu.
np.var(dog_height)

21704.0

In [72]:
np.sqrt(dog_height) # sqrt : căn bậc hai

array([24.49489743, 21.67948339, 13.03840481, 20.73644135, 17.32050808])

In [73]:
# Để tính độ lệch chuẩn chúng ta cùng có thể dùng căn bậc hai của variance
np.sqrt(np.var(dog_height))

147.32277488562318

### Sorting Arrays
np.sort uses an quicksort algorithm

In [74]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [75]:
# A related function is argsort, which instead returns the indices of the sorted elenments:
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

### Sorting along rows or columns
Numpy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument

In [76]:
np.random.seed(42)

MatA = np.random.randint(0,10, size= (4,6))

In [77]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [78]:
np.sort(MatA, axis = 0) # axis = 0 sắp xếp tăng dần theo cột

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [79]:
np.sort(MatA, axis = 1 ) # axis = 1 sắp xếp tăng dần theo hàng


array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [80]:
np.argsort(MatA)

array([[1, 3, 0, 4, 2, 5],
       [0, 4, 3, 1, 2, 5],
       [4, 1, 3, 2, 0, 5],
       [3, 1, 2, 0, 5, 4]], dtype=int64)

### Linear Algebra (Đại Số Tuyến Tính)

In [81]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [82]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

##### Lưu ý : Khi Tích Vô Hướng 2 Ma Trận Thì MatA 'Cột' = MatB 'Hàng' 

In [83]:
#A (3x3) dot product B (3x2)
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [84]:
1*6 + 2*4 + 3*2

20

In [85]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [86]:
#B (3X2) dot A (3X3) : Ta có thể thấy Cột MatB = 2 và Hàng MatA = 3 => Không = nhau nên không thể tích vô hướng 2 matrix này
# Để tích vô hướng 2 matrix này ta có thể dùng chuyển vị 
B.T #(2x3) dot A(3x3)


array([[6, 4, 2],
       [5, 3, 1]])

In [87]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [88]:
# Number of jars sold 
np.random.seed(0)

sales_amouns = np.random.randint(20,size=(5,3))
sales_amouns

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [89]:
# Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amouns, index= ["Mon", "Tues", "Wed", "Thurs","Fri"],
                                            columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [90]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [91]:
# Create a price array
prices = np.array([10,8,12])
prices.shape

(3,)

In [92]:
butter_prices = pd.DataFrame(prices.reshape(1,3) , index = ["prices"] , columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
prices             10              8             12

In [93]:
weekly_sales.shape, butter_prices.T.shape

((5, 3), (3, 1))

In [94]:
total_price = weekly_sales @ butter_prices.T
total_price

prices
Mon       240
Tues      138
Wed       458
Thurs     232
Fri       142

In [95]:
weekly_sales["Total_price"] = total_price
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total_price
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142