In [1085]:
import numpy as np

## Creating Numpy Arrays From Python Lists
(Tạo mảng Numpy từ danh sách Python)

In [1086]:
# np.array([1,2,3,4]) tạo ra một mảng một chiều gồm 4 phần tử: 1, 2, 3, và 4 bằng thư viện NumPy của Python.
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [1087]:
# Array có thể chứa Float và Int
[3.14, 4,2,3]

[3.14, 4, 2, 3]

In [1088]:
# Khi trong array có 2 kiểu dữ liệu thì nó sẽ kiểu dữ liệu lớn hơn
# Dưới đây kiểu dữ liệu Float64 lớn hơn Int32 nên sẽ chuyển dữ liệu trong array sang kiểu dữ liệu lớn hơn là Float64
np.array([3.14, 4 , 2 , 3])

array([3.14, 4.  , 2.  , 3.  ])

In [1089]:
# Ép kiểu dữ liệu của Array sang Float 32bit
c = np.array([1,2,3,4],dtype = 'float32')
c

array([1., 2., 3., 4.], dtype=float32)

In [1090]:
# shape trả về kích trước của mảng (hàng,cột)
a2 = np.array([[1,2,3,4]])
a2.shape

(1, 4)

In [1091]:
# ndim trả về số chiều của mảng
a2.ndim

2

In [1092]:
# dtype trả về kiểu dữ liệu của phần tử trong mảng
a2.dtype

dtype('int32')

In [1093]:
# size trả về số lượng phần tử trong mảng
a2.size

4

## Creating Numpy Arrays From Scatch 
(Tạo mảng NumPy từ đầu)

##### zeros, ones, full, arange, linspace

In [1094]:
# zeros là một hàm trong thư viện NumPy của Python được sử dụng để tạo ra một mảng mới với các phần tử bằng 0.
# Cú pháp sử dụng hàm zeros như sau: numpy.zeros(shape, dtype=float, order='C')
# Trong đó:
# shape: là tuple hoặc list chứa kích thước của mảng mới cần tạo.
# dtype: là kiểu dữ liệu của các phần tử trong mảng mới. Giá trị mặc định là float64.
# order: xác định cách mảng được lưu trữ trong bộ nhớ. Giá trị mặc định là 'C', tương đương với cách lưu trữ theo thứ tự "C-style", tức là theo chiều dọc.

np.zeros([4,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [1095]:
# Tương tự như hàm zeros có điều nó sẽ giá trị phần tử trong mảng trả về là 1
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [1096]:

# arange là một hàm trong thư viện NumPy của Python để tạo ra một mảng các số nguyên hoặc số thực liên tiếp với một khoảng cách cố định giữa chúng.
# Cú pháp của hàm arange như sau: numpy.arange([start, ]stop, [step, ]dtype=None)
# Trong đó:
# start: giá trị đầu tiên trong mảng (mặc định là 0 nếu không được cung cấp).
# stop: giá trị cuối cùng trong mảng (không bao gồm giá trị này trong mảng).
# step: khoảng cách giữa các giá trị trong mảng (mặc định là 1 nếu không được cung cấp).
# dtype: kiểu dữ liệu của mảng (mặc định là kiểu dữ liệu của start nếu không được cung cấp).
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [1097]:
# Hàm numpy.full trong thư viện NumPy được sử dụng để tạo một mảng với tất cả các phần tử có giá trị bằng nhau.
# Cú pháp của hàm numpy.full như sau: numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
# Trong đó:
# shape: kích thước của mảng được tạo ra (có thể là một tuple hoặc một số nguyên).
# fill_value: giá trị để điền vào tất cả các phần tử của mảng.
# dtype (tuỳ chọn): kiểu dữ liệu của mảng (mặc định là None, tức là sử dụng kiểu dữ liệu của fill_value).
# order (tuỳ chọn): thứ tự lưu trữ của mảng ('C' cho C-style, hoặc 'F' cho Fortran-style).
# like (tuỳ chọn): một mảng khác để sao chép kích thước và kiểu dữ liệu của mảng được tạo ra.
np.full([3,5],2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [1098]:
# linspace là một hàm của thư viện NumPy được sử dụng để tạo ra một mảng Numpy chứa các giá trị được phân bố đều trong một khoảng giá trị cho trước.
# Cú pháp của hàm numpy.linspace như sau:numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# Trong đó:
# start: giá trị đầu tiên của khoảng giá trị.
# stop: giá trị cuối cùng của khoảng giá trị.
# num (tuỳ chọn): số lượng các giá trị được tạo ra (mặc định là 50).
# endpoint (tuỳ chọn): xác định xem giá trị stop có nằm trong khoảng giá trị được tạo ra hay không (mặc định là True).
# retstep (tuỳ chọn): xác định xem có trả về khoảng cách giữa các giá trị hay không (mặc định là False).
# dtype (tuỳ chọn): kiểu dữ liệu của mảng được tạo ra (mặc định là None, tức là sử dụng kiểu dữ liệu mặc định của NumPy).
# axis (tuỳ chọn): trục để tạo mảng (mặc định là 0).
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### random


In [1099]:
np.random.seed(0) # trỏ vào 0

np.random.random((4,4)) # nhảy số ngẫu nhiên trong phạm vi từ 0.0 cho tới 1.0

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [1100]:
np.random.seed(0) # trỏ vào 0
np.random.random((4,4)) # nhảy số ngẫu nhiên trong phạm vi từ 0.0 cho tới 1.0

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [1101]:
# rand tương tự như random nhưng không cần ()
np.random.rand(4,4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [1102]:
# ma trận 3x3 với các giá trị được lấy ngẫu nhiên theo phân phối chuẩn, với giá trị trung bình bằng 0 và độ lệch chuẩn bằng 1.
np.random.normal(0,1,(3,3)) 


array([[ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575]])

In [1103]:
# ma trận 4x5 với giá trị ngẫu nhiên từ 0 - 10
np.random.randint(0,10,(4,5))

array([[1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3],
       [5, 9, 4, 4, 6],
       [4, 4, 3, 4, 4]])

## Array Indexing & Slicing


#### One-dimensional subarray (Mảng 1 chiều)

In [1104]:
x1 = np.random.randint(20, size = 6)
x1

array([ 8, 14, 15,  3, 15, 13])

In [1105]:
x1[0], x1[1]

(8, 14)

#### Multi-dimensional array (Mảng 2 chiều)

In [1106]:
x2 = np.random.randint(10, size = (3,4))
x2

array([[5, 5, 0, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

In [1107]:
x2[0,3],x2[2,3]

(1, 2)

In [1108]:
x2[0,2] = 6

In [1109]:
x2

c:\ProgramData\anaconda3\lib\site-packages\IPython\core\displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


array([[5, 5, 6, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

#### Slicing
x[start:stop:step]

In [1110]:
x1

array([ 8, 14, 15,  3, 15, 13])

In [1111]:
x1[0:3]

array([ 8, 14, 15])

In [1112]:
# every other element, every 2 step
x1[::2]

array([ 8, 15, 15])

In [1113]:
x2

array([[5, 5, 6, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

In [1114]:
x2[0:3][0:3]
# Giả sử x2 là một mảng hai chiều, thì x2[0:2][0:3] được hiểu như sau:

# x2[0:2] sẽ trả về một mảng mới gồm các hàng từ hàng thứ 0 đến hàng thứ 1 của mảng x2 (lưu ý rằng chỉ số của hàng bắt đầu từ 0). Do đó, kết quả sẽ là một mảng hai chiều mới có số hàng là 2.
# Tiếp theo, với mảng hai chiều mới này, ta sử dụng chỉ số [0:3] để truy xuất các phần tử của các hàng trong mảng mới. Với chỉ số này, ta sẽ lấy các phần tử từ cột đầu tiên đến cột thứ 2 (lưu ý rằng chỉ số của cột cũng bắt đầu từ 0).
# Vậy kết quả cuối cùng sẽ là một mảng 2x3, bao gồm 2 hàng và 3 cột, chứa các phần tử của hàng 0 và 1 của mảng ban đầu, và cột 0 đến cột 2 của các hàng đó.

array([[5, 5, 6, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

#### Reshaping of Arrays & Transpose (Thay đổi hình dạng của mảng)

In [1115]:
# shape trả về kích trước của mảng (hàng,cột)
grid = np.arange(1,10)
grid.shape

(9,)

In [1116]:
# reshapre thay đổi kích thước của mảng
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1117]:
x = np.array([1,2,3])
x.shape

(3,)

In [1118]:
x.reshape((1,3)).shape

(1, 3)

In [1119]:
x = np.array([[1. ,2.],[3., 4.]])

In [1120]:
x

array([[1., 2.],
       [3., 4.]])

In [1121]:
#  được sử dụng để trả về ma trận chuyển vị (transpose) của mảng. Khi sử dụng T, các cột của mảng ban đầu trở thành các hàng của ma trận mới và ngược lại, 
# các hàng của mảng ban đầu trở thành các cột của ma trận mới.
x.T

array([[1., 3.],
       [2., 4.]])

### Array Concatenation(Nối mảng)  and Splitting(Tách mảng)

In [1122]:
x =  np.array([1,2,3])
y =  np.array([3,4,5])

In [1123]:
np.concatenate((x,y))

array([1, 2, 3, 3, 4, 5])

In [1124]:
grid = np.array([[1,2,3], # Mặc định : axis = 0 nối theo hàng
                 [4,5,6]])
grid


array([[1, 2, 3],
       [4, 5, 6]])

In [1125]:
np.concatenate((grid,grid),axis = 1) # axis = 1 thì nối theo cột

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [1126]:
#vstack nối mảng theo hàng
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

In [1127]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [1128]:
# horizontally stack the arrays: hstack : nối mảng theo cột
y = np.array([[99],
              [99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

### Splitting of arrays

In [1129]:
# split cắt mảng 
# cú pháp np.split(arr,[index])
# arr : mảng muốn cắt
# [index] : khoảng cách cắt
x = np.array([1,2,3,99,69,3,2,1])
x1, x2, x3, x4 =np.split(x,[2,4,6])

In [1130]:
x1

array([1, 2])

In [1131]:
x2

array([ 3, 99])

In [1132]:
x3

array([69,  3])

In [1133]:
x4

array([2, 1])

### Broadcasting and Vetorized operations
##### Broadcasting is simply a set of ruler for applying binary ufuns(e.g., additon, subtraction, multiplication, etc.) on arrays of different size