In [3707]:
import pandas as pd
import numpy as np

df = pd.read_csv("chipotle.tsv", sep="\t")
df.head(5)


order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [3708]:
df.shape

(4622, 5)

In [3709]:
df.size

23110

In [3710]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


In [3711]:
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [3712]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [3713]:
df.describe(include = "all")

order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75 
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [3714]:
df.item_price = df.item_price.apply(lambda x : float(x.replace('$','')))
df.describe()

order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

In [3715]:
df.head(5)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

In [3716]:
df.loc[(df.item_name == "Izze") & (df.item_price == 3.39) ]

order_id  quantity item_name choice_description  item_price
1            1         1      Izze       [Clementine]        3.39
24          12         1      Izze       [Grapefruit]        3.39
47          21         1      Izze       [Blackberry]        3.39
66          30         1      Izze       [Blackberry]        3.39
359        155         1      Izze       [Blackberry]        3.39
360        155         1      Izze       [Grapefruit]        3.39
430        186         1      Izze       [Grapefruit]        3.39
579        237         1      Izze       [Clementine]        3.39
580        237         1      Izze       [Grapefruit]        3.39
1059       436         1      Izze       [Clementine]        3.39
1213       495         1      Izze       [Clementine]        3.39
1611       651         1      Izze       [Blackberry]        3.39
1612       651         1      Izze       [Blackberry]        3.39
1680       680         1      Izze       [Clementine]        3.39
2088       842         1      Izze       [Clementine]        3.39
2619      1040         1      Izze       [Clementine]        3.39
2634      1046         1      Izze       [Clementine]        3.39
2758      1095         1      Izze       [Blackberry]        3.39
2891      1149         1      Izze       [Blackberry]        3.39
3669      1468         1      Izze       [Blackberry]        3.39

In [3717]:
df["Total_Price"] = df.quantity	* df.item_price
df.head(5)


order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  Total_Price  
0                                                NaN        2.39         2.39  
1                                       [Clementine]        3.39         3.39  
2                                            [Apple]        3.39         3.39  
3                                                NaN        2.39         2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98        33.96

In [3718]:
df["Total_Price"].sum()

39237.02

In [3719]:
c = df.groupby("item_name")["quantity"].sum()
c.sort_values(ascending= False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

In [3720]:
df.item_name.nunique()

50

In [3721]:
c = np.array([1,2,3,4])
c[0]

1

In [3722]:
c.size

4

In [3723]:
c.shape

(4,)

In [3724]:
c = c.reshape((1,4))

In [3725]:
c.shape

(1, 4)

In [3726]:
c

array([[1, 2, 3, 4]])

In [3727]:
c.ndim

2

In [3728]:
c.dtype

dtype('int32')

In [3729]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [3730]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [3731]:
a = np.arange(1,10,1)
a = a.reshape((3,3))

In [3732]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3733]:
a.ndim, a.shape

(2, (3, 3))

In [3734]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [3735]:
np.linspace(1,100,10,dtype=int)

c:\ProgramData\anaconda3\lib\site-packages\IPython\core\displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'


array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [3736]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [3737]:
np.random.seed(0)
np.random.random((4,4))


array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [3738]:
np.random.rand(4,4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [3739]:
np.random.normal(0,1,(3,3))

array([[ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575]])

In [3740]:
np.random.randint(1,10,(4,5))

array([[2, 8, 4, 7, 8],
       [3, 1, 4, 6, 5],
       [5, 7, 5, 5, 4],
       [5, 5, 9, 5, 4]])

In [3741]:
x1 = np.random.randint(20, size = 6)
x1

array([15, 13, 16, 17,  5,  9])

In [3742]:
x1[0]

15

In [3743]:
x2= np.random.randint(10, size = (3,4))
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [3744]:
x2[0,3],x2[1,3]

(0, 2)

In [3745]:
x2[0,2] = 10
x2

array([[ 3,  0, 10,  0],
       [ 1,  2,  4,  2],
       [ 0,  3,  2,  0]])

In [3746]:
x1

array([15, 13, 16, 17,  5,  9])

In [3747]:
x1[0:3]

array([15, 13, 16])

In [3748]:
x1[::2]

array([15, 16,  5])

In [3749]:
x1[:]

array([15, 13, 16, 17,  5,  9])

In [3750]:
x = np.random.randint(1,10,(3,4))
x

array([[8, 6, 1, 3],
       [8, 3, 3, 4],
       [4, 3, 4, 5]])

In [3751]:
x = x.reshape((4,3))
x

array([[8, 6, 1],
       [3, 8, 3],
       [3, 4, 4],
       [3, 4, 5]])

In [3752]:
x.T

array([[8, 3, 3, 3],
       [6, 8, 4, 4],
       [1, 3, 4, 5]])

In [3753]:
grid = np.array([[1,2,3],
                 [3,4,5]])


In [3754]:
np.concatenate((grid,grid),axis= 0)

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [3755]:
np.vstack((grid,grid))

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [3756]:
np.hstack((grid,grid))

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [3757]:
x = np.array([1,2,3,99,69,3,2,1])
x1, x2, x3, x4, x5 = np.split(x,[1,3,5,7])
x1

array([1])

In [3758]:
a =  np.arange(3)
a

array([0, 1, 2])

In [3759]:
a + 5

array([5, 6, 7])

In [3760]:
b = np.ones((3,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3761]:
a.shape,b.shape

((3,), (3, 3))

In [3762]:
c = np.arange(3).reshape(3,1)

In [3763]:
a

array([0, 1, 2])

In [3764]:
c

array([[0],
       [1],
       [2]])

In [3765]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [3766]:
list_n = [1,2,3]
ll = np.array(list_n)
ll 
sum(ll)


6

In [3767]:
np.sum(ll)

6

In [3768]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[4,6],
              [2,4],
              [3,5]])
A @ B

array([[ 17,  29],
       [ 44,  74],
       [ 71, 119]])

In [3769]:
B = B.T


In [3770]:
B.shape

(2, 3)

In [3771]:
B @ A 

array([[33, 42, 51],
       [57, 72, 87]])

In [3772]:
sales_mount = np.random.randint(1,10,size=(3,3))


In [3773]:
df = pd.DataFrame(sales_mount,index=["Hamburge","Pizza","Sting"],
                                columns=["quantity","one","price"])
df

quantity  one  price
Hamburge         2    3      2
Pizza            5    7      9
Sting            3    4      1

In [3774]:
df["total"] = df.quantity * df.price
df

quantity  one  price  total
Hamburge         2    3      2      4
Pizza            5    7      9     45
Sting            3    4      1      3